name: ${project.name}
main: ${groupId}.${project.name}
version: "${project.version}"
author: emanon
api-version: 1.19
folia-supported: true
softdepend: [ Vault,SuperVanish,PremiumVanish,PlaceHolderAPI ]

libraries:
  - net.kyori:adventure-api:4.16.0
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.16.0
  - net.kyori:adventure-text-serializer-gson:4.16.0
  - net.kyori:adventure-text-serializer-legacy:4.16.0

commands:
  displayeditor:
    description: allows to edit item in hand
    usage: /displayeditor
    aliases: [ de ]
  entityeditor:
    description: allows to edit item in hand
    usage: /entityeditor
    aliases: [ ee ]
  displayeditorinfo:
    description: display info of displayeditor
    usage: /displayeditorinfo
  displayeditorreload:
    description: reload configurations
    usage: /displayeditorreload
permissions:
  displayeditor.admin:
    default: op
    description: Gives full access to the plugin
    children:
      displayeditor.displayeditorreload: true
      displayeditor.displayeditorinfo: true
      displayeditor.bypass.*: true
  displayeditor.creativeuser:
    default: op
    description: Gives full access to the plugin
    children:
      displayeditor.displayeditor.*: true
  displayeditor.displayeditor.*:
    default: op
    description: Gives full access to the plugin
    children:
      displayeditor.displayeditor.create: true
      displayeditor.displayeditor.delete: true
      displayeditor.displayeditor.deselect: true
      displayeditor.displayeditor.editormode: true
      displayeditor.displayeditor.select: true
      displayeditor.displayeditor.settext: true
  displayeditor.displayeditor.create:
    default: op
    description: Create new display editors
  displayeditor.displayeditor.delete:
    default: op
    description: Delect current selected display
  displayeditor.displayeditor.select:
    default: op
    description: Select nearest display
  displayeditor.displayeditor.deselect:
    default: op
    description: Deselect current selected display
  displayeditor.displayeditor.editormode:
    default: op
    description: Open the editor mode
  displayeditor.displayeditor.settext:
    default: op
    description: Ability to change text of selected display text
  displayeditor.bypass.*:
    default: op
    description: Gives full access to the plugin
    children:
      displayeditor.bypass.censure: true
  displayeditor.bypass.censure:
    default: op
    description: Bypass words restrictions when editing display text
  displayeditor.displayeditorinfo:
    default: op
    description: Gives full access to command /displayeditorinfo
  displayeditor.displayeditorreload:
    default: op
    description: Gives full access to command /displayeditorreload